package:
  name: star-fusion
  version: 1.7.0

source:
  url: https://github.com/STAR-Fusion/STAR-Fusion/releases/download/v1.7.0/STAR-Fusion-v1.7.0.FULL.tar.gz
  sha256: 86470cad8694253b4305272750193d8d01af8c9049819fcf14f723c85b92fb57

build:
  number: 1
  noarch: generic

requirements:
  run:
    - blast
    - igv-reports
    - perl
    - perl-set-intervaltree
    - perl-carp
    - perl-carp-assert
    - perl-db-file
    - perl-io-gzip
    - perl-json-xs
    - perl-uri
    - star >=2.7.0f
    - gmap
    - bowtie
    - bbmap
    - samtools

test:
  commands:
    - STAR-Fusion --help 2>&1 | grep Optional > /dev/null
    - prep_genome_lib.pl -h 2>&1 | grep "STAR-Fusion" > /dev/null
    - blast_and_promiscuity_filter.pl -h 2>&1 | grep Optional > /dev/null

about:
  home: https://github.com/STAR-Fusion/STAR-Fusion
  license: BSD-3-Clause
  summary: A fusion gene caller for STAR. The FusionFilter tools to create needed index data structures are not included.
